replace if/else block

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,10 +43,8 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          if [ -f requirements-dev.txt ]; then
-            pip install -r requirements-dev.txt
-          else
-            echo "requirements-dev.txt not found, skipping."
+          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt || echo "requirements-dev.txt not found, skipping."
+
 
       - name: Check formatting with Black
         working-directory: ./backend/app
